### ISSUE TITLE
cava config is not efficient

### ISSUE THREAD

**Issue by LukashonakV** [Ruixi-rebirth/sway-dotfiles#1]
Thanks for the cava idea. I decided to use the same idea but I faced with the issue. Your cava.sh consumes a lot of CPU. On my machine in idle mode cava.sh consumes 0.7 of CPU% + cava utility itself consumes 0.6 + Waybar starting consume 1.2CPU% + Sway starting consume 1%CPU. Which is not an efficient. 
I've done next improvements . You can check it

1. cava config [cava.conf](https://gitlab.com/Viktar/dotfiles/-/tree/trunk/.config/waybar/scripts)
2. waybar config [waybar config](https://gitlab.com/Viktar/dotfiles/-/blob/trunk/.config/waybar/config)
`"custom/cava": {
                   "exec": "cava -p $XDG_CONFIG_HOME/waybar/scripts/cava.conf | sed -u 's/;//g;s/0/▁/g;s/1/▂/g;s/2/▃/g;s/3/▄/g;s/4/▅/g;s/5/▆/g;s/6/▇/g;s/7/█/g;'",
    },
`
With such configuration - CPU consumption is decreased significant.

**Comment by Ruixi-rebirth** [comment]
Thank you, I will take your advice.
