### ISSUE TITLE
Wallpapers and fonts

### ISSUE THREAD

**Issue by TQMatvey** [Ruixi-rebirth/sway-dotfiles#2]
Hey! this is a great setup!, trying to replicate this too on gentoo, but cant find the wallpapers(, mind sharing them?

**Comment by Ruixi-rebirth** [comment]
https://github.com/Ruixi-rebirth/wallpaper

**Comment by TQMatvey** [comment]
Thanks!, also some weird thing with icons in waybar, they are well not expected icons :/
I did install all fonts with `emerge nerd-fonts noto twemoji noto-cjk` successfully and enabled fonts via 
`eselect fontconfig enable`

![image](https://github.com/Ruixi-rebirth/sway-dotfiles/assets/77576395/26ee3b31-dd13-427b-9ddc-824d66069650)

**Comment by Ruixi-rebirth** [comment]
Because the previous nerd fonts update deprecated some icons, you will need to change the broken icon characters in the configuration yourself, go to [this website](https://www.nerdfonts.com/cheat-sheet) to find the ones you need

**Comment by TQMatvey** [comment]
alright, thanks a lot!
